### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by gotounix** [huangjia2019/ai-agents#2]
`https://github.com/huangjia2019/ai-agents/blob/main/09-github-agents/9.2_BabyAGI.py` 第 57 行：`class TaskPrioritizationChain(llmChain):` 应为：`class TaskPrioritizationChain(LLMChain):`。

`https://github.com/huangjia2019/ai-agents/blob/main/10-multi-agents/10.1_AutoGen.py` 第 22 行 `llm_config llm_config,` 应为：`llm_config=llm_config,`。

**Comment by huangjia2019** [comment]
感谢您的指出，书籍和代码库都已经修改。在书籍的第7次印刷中将反映出修改。
